---
- name: Install package to maintain clock updated
  apt:
    name: htpdate
    state: present
- name: Install package for open container
  apt:
    name: runc
    state: present
- name: Install package for cgroup
  apt:
    pkg: 
    - cgroup-tools 
    - cgroupfs-mount
- name: Install package for storage
  apt:
    name: open-iscsi
    state: present
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes