---

- hosts: load_balancer
  become: yes
  roles:
    - role: nginx 
  vars:
    nginx_sites:
      - name: kibana
        url: logs.k3s.karva.io
        nginx_backend_servers:
          - address: 192.168.15.88
            port: 5601
          - address: 192.168.15.87
            port: 5601
          - address: 192.168.15.86
            port: 5601
      - name: rancher
        url: rancher.k3s.karva.io
        nginx_backend_servers:
          - address: 192.168.15.88
            port: 443
          - address: 192.168.15.87
            port: 443
          - address: 192.168.15.86
            port: 443
      - name: heimdall
        url: heimdall.k3s.karva.io
        nginx_backend_servers:
          - address: 192.168.15.88
            port: 443
          - address: 192.168.15.87
            port: 443
          - address: 192.168.15.86
            port: 443
      - name: pihole
        url: pihole.k3s.karva.io
        nginx_backend_servers:
          - address: 192.168.15.88
            port: 443
          - address: 192.168.15.87
            port: 443
          - address: 192.168.15.86
            port: 443
    nginx_stream_sites:
      - name: piholeDns
        url: 192.168.15.40
        nginx_default_port: 53 udp
        nginx_backend_servers:
          - address: 192.168.15.88
            port: 53
          - address: 192.168.15.87
            port: 53
          - address: 192.168.15.86
            port: 53