---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pihole-storage-class
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  replicaAutoBalance: "least-effort"
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-volv-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pihole-storage-class
  resources:
    requests:
      storage: 1Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-certificate
  namespace: pihole
spec:
  secretName: pihole-tls
  dnsNames:
    - pihole.k3s.karva.io
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: v1
kind: Pod
metadata:
  name: pihole
  namespace: pihole
spec:
  hostNetwork: true
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      # upstream DNS used by pihole.
      - 8.8.8.8
      - 8.8.4.4
  containers:
    - name: pihole
      # https://hub.docker.com/r/pihole/pihole/tags
      image: pihole/pihole:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: WEBPASSWORD
          value: "EFIhNlLa"
      securityContext:
        privileged: true
      ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 67
          protocol: UDP
        - containerPort: 443
          protocol: TCP
      volumeMounts:
        - name: etc
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 2Gi
          cpu: 1
  volumes:
    - name: etc
      hostPath:
        path: /data/pihole/etc
        type: Directory
    - name: dnsmasq
      hostPath:
        path: /data/pihole/dnsmasq.d
        type: Directory
---
