---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: logs-management
  labels:
    app: curator
data:
  action_file.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    #
    # Also remember that all examples have 'disable_action' set to True.  If you
    # want to use this action as a template, be sure to set this to False after
    # copying it.
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(metric|heart|file)beat-.*$'
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 3
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - elasticsearch-logging
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
---
apiVersion: batch/v1 #for API server versions >= 1.8.0 use batch/v1beta1
kind: CronJob
metadata:
  name: curator
  namespace: logs-management
  labels:
    app: curator
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ingestor
            image: python:alpine3.15
            args: ["sh", "-c", "pip install elasticsearch-curator && \
                    curator --config /etc/config/config.yml /etc/config/action_file.yml || \
                    true"]
            volumeMounts:
            - name: config
              mountPath: /etc/config
          volumes:
          - name: config
            configMap:
              name: curator-config
      backoffLimit: 1
---